services:
    nginx:
        image: nginx:1.20-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '443:443'
            - '80:80'
        depends_on:
            - auth

    auth:
        build: .
        container_name: auth
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 8080
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine
