services:
    auth:
        build:
            context: https://github.com/argoroots/est-o-auth.git
        container_name: auth
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 8080

    nginx:
        image: nginx:1.20-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '443:443'
            - '80:80'
        depends_on:
            - auth

    redis:
        image: redis:6.2-alpine
