services:
    auth:
        build:
            context: https://github.com/argoroots/est-o-auth.git#main
        container_name: auth
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine

    nginx:
        image: nginx:1.20-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            AUTH_DOMAIN: auth.test
            IDCARD_DOMAIN: id.auth.test
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on:
            - auth
            - certbot

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: certonly --dry-run --webroot --webroot-path=/var/www/certbot --agree-tos -d auth.test -d id.auth.test
