services:
    auth:
        build: .
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine

    nginx:
        image: nginx:1.20-alpine
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            AUTH_DOMAIN: auth.test
            IDCARD_DOMAIN: id.auth.test
        volumes:
            - ./nginx/letsencrypt.conf.template:/etc/nginx/templates/letsencrypt.conf.template:ro
            - ./data/certbot/www:/var/www/certbot:ro

    nginx_ssl:
        image: nginx:1.20-alpine
        restart: unless-stopped
        ports:
            - 443:443
        environment:
            AUTH_DOMAIN: auth.test
            IDCARD_DOMAIN: id.auth.test
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
            - ./nginx/id-card.conf.template:/etc/nginx/templates/id-card.conf.template:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
        depends_on:
            - auth
            - certbot

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email --email test@auth.test -d auth.entu.app -d id.auth.entu.app
        # command: renew --webroot --webroot-path=/var/www/certbot --agree-tos --no-eff-email --email test@auth.test
