services:
    auth:
        build: .
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            NODE_ENV: production
            PORT: 80
            NUXT_URL: ${NUXT_URL}
            NUXT_JWT_SECRET: ${NUXT_JWT_SECRET}
            NUXT_EMAIL_FROM: ${NUXT_EMAIL_FROM}
            NUXT_AWS_ID: ${NUXT_AWS_ID}
            NUXT_AWS_SECRET: ${NUXT_AWS_SECRET}
            NUXT_AWS_REGION: ${NUXT_AWS_REGION}
            NUXT_SKID_NAME: ${NUXT_SKID_NAME}
            NUXT_SKID_UUID: ${NUXT_SKID_UUID}
            NUXT_APPLE_ID: ${NUXT_APPLE_ID}
            NUXT_APPLE_TEAM: ${NUXT_APPLE_TEAM}
            NUXT_APPLE_SECRET: ${NUXT_APPLE_SECRET}
            NUXT_GOOGLE_ID: ${NUXT_GOOGLE_ID}
            NUXT_GOOGLE_SECRET: ${NUXT_GOOGLE_SECRET}
