services:
    nginx:
        image: nginx:1.20-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
        environment:
            AUTH_DOMAIN: auth.test
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
        depends_on:
            - auth

    auth:
        build: .
        container_name: auth
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine
