services:
    build:
        build: ./web
        restart: 'no'
        environment:
            NODE_ENV: production
            VITE_APP_IDCARD_DOMAIN: ${IDCARD_DOMAIN}
        volumes:
            - ./data/public:/usr/src/est-o-auth/dist

    auth:
        build: ./api
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
            REDIS: redis://redis:6379
            JWT_SECRET: ${JWT_SECRET}
            EMAIL_FROM: ${EMAIL_FROM}
            EMAIL_URL: https://${DOMAIN}/auth/e-mail
            AWS_SES_ID: ${AWS_SES_ID}
            AWS_SES_KEY: ${AWS_SES_KEY}
            AWS_SES_REGION: ${AWS_SES_REGION}
            MOBILEID_NAME: ${MOBILEID_NAME}
            MOBILEID_UUID: ${MOBILEID_UUID}
            SMARTID_NAME: ${SMARTID_NAME}
            SMARTID_UUID: ${SMARTID_UUID}
        depends_on:
            - redis

    redis:
        image: redis:7.0-alpine

    nginx:
        image: nginx:1.20-alpine
        restart: unless-stopped
        ports:
            - 443:443
        environment:
            DOMAIN: ${DOMAIN}
            IDCARD_DOMAIN: ${IDCARD_DOMAIN}
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
            - ./nginx/id-card.conf.template:/etc/nginx/templates/id-card.conf.template:ro
            - ./data/id-card:/etc/id-card:ro
            - ./data/id-card/dhparam.pem:/etc/nginx/dhparam.pem:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
            - ./data/logs:/etc/nginx/logs
            - ./data/public:/etc/nginx/html:ro
        depends_on:
            - auth
