services:
    build:
        build: ./web
        restart: 'no'
        environment:
            NODE_ENV: production
        volumes:
            - ./data/public:/usr/src/est-o-auth/dist

    auth:
        build: ./api
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
            REDIS: redis://redis:6379
            DOMAIN: ${DOMAIN}
            JWT_SECRET: ${JWT_SECRET}
            EMAIL_FROM: ${EMAIL_FROM}
            AWS_SES_ID: ${AWS_SES_ID}
            AWS_SES_KEY: ${AWS_SES_KEY}
            AWS_SES_REGION: ${AWS_SES_REGION}
            MOBILEID_NAME: ${MOBILEID_NAME}
            MOBILEID_UUID: ${MOBILEID_UUID}
            SMARTID_NAME: ${SMARTID_NAME}
            SMARTID_UUID: ${SMARTID_UUID}
            APPLE_ID: ${APPLE_ID}
            APPLE_SECRET: ${APPLE_SECRET}
            APPLE_TEAM: ${APPLE_TEAM}
            GOOGLE_ID: ${GOOGLE_ID}
            GOOGLE_SECRET: ${GOOGLE_SECRET}
            CLIENTS_YAML: /usr/src/est-o-auth/clients.yaml
        volumes:
            - ./data/clients.yaml:/usr/src/est-o-auth/clients.yaml:ro
        depends_on:
            - redis

    redis:
        image: redis:7.0-alpine

    nginx:
        image: nginx:1.22-alpine
        restart: unless-stopped
        ports:
            - 443:443
        environment:
            DOMAIN: ${DOMAIN}
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
            - ./data/logs:/etc/nginx/logs
            - ./data/public:/etc/nginx/html:ro
        depends_on:
            - auth
