services:
    build:
        build: ./web
        restart: 'no'
        environment:
            NODE_ENV: production
            VITE_APP_IDCARD_DOMAIN: ${IDCARD_DOMAIN}
        volumes:
            - ./data/public:/usr/src/est-o-auth/dist

    auth:
        build: ./api
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
            REDIS: redis://redis:6379
            JWT_SECRET: ${JWT_SECRET}
            EMAIL_FROM: ${EMAIL_FROM}
            EMAIL_URL: https://${DOMAIN}/auth/e-mail
            AWS_SES_ID: ${AWS_SES_ID}
            AWS_SES_KEY: ${AWS_SES_KEY}
            AWS_SES_REGION: ${AWS_SES_REGION}
            MOBILEID_NAME: ${MOBILEID_NAME}
            MOBILEID_UUID: ${MOBILEID_UUID}
            SMARTID_NAME: ${SMARTID_NAME}
            SMARTID_UUID: ${SMARTID_UUID}
            CLIENTS_YAML: /usr/src/entu-auth/clients.yaml
        volumes:
            - ./data/clients.yaml:/usr/src/entu-auth/clients.yaml:ro
        depends_on:
            - redis

    entu-auth:
        build:
            context: https://github.com/entu/auth.git#main
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
            COOKIE_DOMAIN: ${ENTU_AUTH_COOKIE_DOMAIN}
            MONGODB: ${ENTU_AUTH_MONGODB}
            MID_NAME: ${MOBILEID_NAME}
            MID_UUID: ${MOBILEID_UUID}
            GOOGLE_ID: ${GOOGLE_ID}
            GOOGLE_SECRET: ${GOOGLE_SECRET}
            FACEBOOK_ID: ${FACEBOOK_ID}
            FACEBOOK_SECRET: ${FACEBOOK_SECRET}
        volumes:
            - ./data/do-mongodb-ca-certificate.crt:/usr/src/entu-auth/ca/certificate.crt:ro

    redis:
        image: redis:7.0-alpine

    nginx:
        image: nginx:1.22-alpine
        restart: unless-stopped
        ports:
            - 443:443
        environment:
            DOMAIN: ${DOMAIN}
            IDCARD_DOMAIN: ${IDCARD_DOMAIN}
            ENTU_AUTH_DOMAIN: ${ENTU_AUTH_DOMAIN}
            ENTU_AUTH_IDCARD_DOMAIN: ${ENTU_AUTH_IDCARD_DOMAIN}
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
            - ./nginx/id-card.conf.template:/etc/nginx/templates/id-card.conf.template:ro
            - ./nginx/entu-auth.conf.template:/etc/nginx/templates/entu-auth.conf.template:ro
            - ./nginx/entu-auth.id-card.conf.template:/etc/nginx/templates/entu-auth.id-card.conf.template:ro
            - ./data/id-card:/etc/id-card:ro
            - ./data/id-card/dhparam.pem:/etc/nginx/dhparam.pem:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
            - ./data/logs:/etc/nginx/logs
            - ./data/public:/etc/nginx/html:ro
        depends_on:
            - auth
