services:
    auth:
        build: .
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 80
            REDIS: redis://redis:6379
            JWT_SECRET: ${JWT_SECRET}
        depends_on:
            - redis

    redis:
        image: redis:6.2-alpine

    nginx:
        image: nginx:1.20-alpine
        restart: unless-stopped
        ports:
            - 443:443
        environment:
            DOMAIN: ${DOMAIN}
            IDCARD_DOMAIN: ${IDCARD_DOMAIN}
        volumes:
            - ./nginx/auth.conf.template:/etc/nginx/templates/auth.conf.template:ro
            - ./nginx/id-card.conf.template:/etc/nginx/templates/id-card.conf.template:ro
            - ./data/id-card:/etc/id-card:ro
            - ./data/id-card/dhparam.pem:/etc/nginx/dhparam.pem:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
        depends_on:
            - auth
